version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0
    ports:
    - 4444:4444
  selenium_video:
    image: selenium/video:ffmpeg-4.3.1-20210604
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - selenium
    environment:
      - DISPLAY_CONTAINER_NAME=selenium
      - FILE_NAME=chrome_video.mp4
  scraper:
    build: .
    depends_on:
      - tor
    environment:
      - token=${PUSHOVER_TOKEN}
      - user=${PUSHOVER_USER}
      - code1=${CODE_1}
      - code2=${CODE_2}
      - code3=${CODE_3}
  tor:
    image: dperson/torproxy
    environment:
      - TOR_NewCircuitPeriod=30
      - TOR_MaxCircuitDirtiness=30