version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0
    ports:
    - 4444:4444
  scraper:
    build: .
    depends_on:
      - tor
    environment:
      - token=${PUSHOVER_TOKEN}
      - user=${PUSHOVER_USER}
      - code1=${CODE_1}
      - code2=${CODE_2}
      - code3=${CODE_3}
  tor:
    image: dperson/torproxy
    environment:
      - TOR_NewCircuitPeriod=30
    ports:
    - 8118:8118
    - 9050:9050