version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0
    ports:
    - 4444:4444
  scraper:
    build: .
    environment:
      - token=${PUSHOVER_TOKEN}
      - user=${PUSHOVER_USER}